mercadinho_do_seu_luis/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.urls import path, include
from django.contrib import admin

import mercado.urls
import users.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(mercado.urls)),
    path('users/', include(users.urls))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mercado/urls.py
from django.urls import path

from mercado.views.PesquisaView import PesquisaView
from .views import *

app_name = 'mercado'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('product/category/<slug:slug>/', CategoriaProdutoView.as_view(), name="categoria-produto"),
    path('produto/all/', MeusProdutoView.as_view(), name="meus-produtos"),
    path('product/add/', AdicionarProdutoView.as_view(), name="adicionar-produto"),
    path('product/<int:pk>/edit', EditarProdutoView.as_view(), name="editar-produto"),
    # path('produto/delete/<int:id>', DeleteProdutoView.as_view(), name="delete-produto")
    path('product/<int:id>/', ProdutoView.as_view(), name="produto"),

    path('carrinho/', CarrinhoView.as_view(), name="carrinho"),
    path('carrinho/adicionar/<int:produto_id>', AddCarrinhoView.as_view(), name="adicionar-carrinho"),
    path('carrinho/remover/<int:carrinho_id>', RemoverCarrinhoView.as_view(), name="remover-carrinho"),

    path('search/', PesquisaView.as_view(), name="pesquisa")
]

users/urls.py
# import django
from django.urls import  path
from users.views import *

app_name = "users"

urlpatterns = [
    path('register/', RegisterUsuarioView.as_view(), name="register"),
    path('register-vendedor/', RegisterVendedorView.as_view(), name="register-vendedor"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
]

mercado/models/Carrinho.py
from hashlib import blake2s
from django.db import models

class Carrinho(models.Model):
    usuario = models.ForeignKey(
        'users.Usuario',
        on_delete=models.CASCADE
    )

    data_criacao = models.DateTimeField(
        auto_now_add=True,
        # auto_created=True,
        verbose_name="Data de criação"
    )

    produto = models.ForeignKey(
        'mercado.Produto',
        on_delete=models.CASCADE
    )

    quantidade = models.IntegerField(
        verbose_name="Quantidade",
        default=1,
        blank=False,
        null=False
    )

    def get_preco_total_produto(self):
        if self.produto.com_desconto is True:
            desconto_em_reais = self.produto.preco * (self.produto.desconto / 100)
            preco_produto = self.produto.preco - desconto_em_reais
        else:
            preco_produto = self.produto.preco

        preco_produto_final = preco_produto * self.quantidade

        return self.produto.get_preco_formatado(preco_produto_final)

    def __str__(self):
        return self.produto.nome

mercado/models/Categoria.py
from django.db import models

class Categoria(models.Model):
    nome = models.CharField(
        verbose_name="Categoria",
        max_length=96
    )

    slug = models.SlugField(
        verbose_name="Slug da categoria",
        unique=True,
        null=True
    )

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
        db_table = "categoria"

    def __str__(self):
        return self.nome

mercado/models/Produto.py
from io import BytesIO
from django.urls import reverse
from django.db import models
from django.core.files.base import ContentFile
import locale
from PIL import Image
from mercado.models.Categoria import Categoria

# Create your models here.
class Produto(models.Model):
    nome = models.CharField(
        verbose_name="Nome",
        blank=False,
        null=False,
        max_length=96,
        help_text='Ex: Motorola Moto g10',
    )

    descricao = models.TextField(
        verbose_name="Descrição",
        help_text="Ex: Este é o melhor produto do mundo"
    )

    descricao_html = models.TextField(
        verbose_name="Descrição em HTML",
        help_text="Ex: <h1>Este é o melhor produto do mundo</h1>",
        blank=True,
        null=True
    )

    is_descricao_html = models.BooleanField(
        default=False
    )

    is_ativo = models.BooleanField(default=False)

    preco = models.FloatField(
        verbose_name="Preço",
        blank=False,
        null=False,

    )

    vendedor = models.ForeignKey(
        'users.Vendedor',
        on_delete=models.CASCADE,
        null=True,
    )

    imagem = models.ImageField(upload_to="mercado/covers/%Y/%m/%d/")

    categoria = models.ForeignKey(
        'Categoria',
        on_delete=models.SET_NULL,
        null=True
    )

    desconto = models.FloatField(
        verbose_name="Porcentagem do desconto",
        blank=True,
        null=True
    )

    com_desconto = models.BooleanField(
        verbose_name="O Produto está com desconto",
        blank=True
    )

    data_criacao = models.DateField(
        verbose_name="Data de criação",
        auto_now=True,
    )

    def save(self, *args, **kwargs):
        if self.descricao_html:
            self.is_descricao_html = True
        else:
            self.is_ativo = True

        pil_image_obj = Image.open(self.imagem)
        pil_image_obj.thumbnail((100, 100), Image.ANTIALIAS)

        new_image_io = BytesIO()
        pil_image_obj.save(new_image_io, pil_image_obj.format)

        temp_name = self.imagem.name
        self.imagem.delete(save=False)  

        self.imagem.save(
            temp_name,
            content=ContentFile(new_image_io.getvalue()),
            save=False
        )

        
        return super(Produto, self).save(*args, **kwargs)   

    def get_absolute_url(self, **kwargs):
        return reverse('mercado:produto', kwargs={'id': self.id})
    
    def get_preco_formatado(self, preco):
        locale.setlocale( locale.LC_ALL, '' )
        preco_formatado = locale.currency(preco, symbol=False, grouping=True)
        return preco_formatado

    def get_preco(self, *args, **kwargs):
        preco_formatado = self.get_preco_formatado(self.preco)
        return preco_formatado

    def get_quantidade_desconto(self, *args, **kwargs):
        desconto = self.desconto
        return f'{int(desconto)}%'

    def get_preco_com_desconto(self, *args, **kwargs):
        if self.desconto is None:
            preco_formatado = self.get_preco(   )
        else:
            desconto_em_reais = self.preco * (self.desconto / 100)

            preco_desconto = self.preco - desconto_em_reais

            preco_formatado = self.get_preco_formatado(preco_desconto)

        return preco_formatado

    def __str__(self):
        return self.nome

mercado/models/Produtos.py
from distutils.command.upload import upload
from tabnanny import verbose
from django.db import models

# Create your models here.
class Produto(models.Model):
    nome = models.CharField(
        verbose_name="Nome",
        blank=False,
        null=False,
        max_length=96
    )

    descricao = models.TextField(
        verbose_name="Descrição",
    )

    descricao_html = models.TextField(
        verbose_name="Descrição em HTML",
    )

    preco = models.IntegerField(
        verbose_name="Preço",
        blank=False,
        null=False
    )

    vendendor = models.ForeignKey(
        'Vendedor',
        on_delete=models.CASCADE,
    )

    imagem = models.ImageField(upload_to="mercado/covers/%Y/%m/%d/", null=True)

    def __str__(self):
        return self.nome

mercado/models/Vendedor.py
from django.contrib.auth.models import User
from django.db import models

class Vendedor(models.Model):
    # usuario = models.OneToOneField(
    #     'User', # Nâo funciona, Por que não é um model
    #     verbose_name="Usuário",
    #     on_delete=models.CASCADE
    # )

    nome_loja = models.TextField(
        verbose_name="Nome da loja"
    )

    nome_completo = models.TextField(
        verbose_name="Nome completo",
    )

    cnpj = models.TextField(
        verbose_name="CNPJ",
        blank=False,
        null=False,
        max_length=14
    )

    endereco = models.TextField(
        verbose_name="Endereço",

    )

    telefone = models.TextField(
        verbose_name="Telefone",
        max_length=11
    )

    def __str__(self):
        return self.nome_completo

users/models/Carrinho.py
from django.db import models

class Carrinho(models.Model):
    user = models.ForeignKey(
        'users.Usuario',
        on_delete=models.CASCADE
    )

    data_criacao = models.DateTimeField(
        auto_created=True,
        verbose_name="Data de criação"
    )

    produto = models.ForeignKey(
        'mercado.Produto',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.produto__nome

mercado/forms/ProdutoForm.py
from mercado.models.Produto import Produto
from django import forms

class ProdutoForm(forms.ModelForm):


    nome = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'span-3'
            }
        )
    )

    descricao = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'span-3'
            }
        )
    )

    descricao_html = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'span-3'
            }
        ),
        required=False
    )

    com_desconto = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'class': 'label-row'
            }
        )
    )

    

    imagem = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'class': 'label-imagem',
                'data': 'inputImage'}
        )
    )
    
    class Meta:
        model = Produto
        fields = [
            'nome', 'descricao',
            'descricao_html', 'preco',
            'imagem', 'categoria',
            'desconto', 'com_desconto'
        ]

    def clean(self):

        cleaned_data = super().clean()

        com_desconto = cleaned_data.get('com_desconto')
        quant_desconto = cleaned_data.get('desconto')
        if com_desconto is True:

            if quant_desconto is None:
                self.add_error('desconto', 'Informe a quantidade de desconto')

            if quant_desconto < 0 or quant_desconto > 100:
                self.add_error('desconto', 'Insira um valor entre 0 à 100')


        return super().clean()

mercado/views/CarrinhoView.py
from re import template
from django.shortcuts import redirect
from django.views import View
from django.views.generic.list import ListView
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from mercado.models.Carrinho import Carrinho
from mercado.models.Produto import Produto


# ver forma melhor de criar o Carrinho

class CarrinhoView(LoginRequiredMixin, ListView):
    template_name = 'mercado/pages/carrinho.html'
    model = Carrinho
    contect_object_name = 'produtos'
    ordering = ['-id']

    def get_queryset(self):
        return super().get_queryset().filter(usuario__id=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["titulo_da_pagina"] = "Carrinho"
        return context

class AddCarrinhoView(LoginRequiredMixin, View):
    model = Carrinho
    success_url = 'mercado:home'

    def get(self, request, produto_id):
        produto = Produto.objects.get(id=produto_id)
        usuario = request.user

        carrinho = Carrinho.objects.get_or_create(usuario=usuario, produto=produto)
        print(request)

        return redirect('mercado:carrinho')

    def post(self, request, produto_id):
        produto = Produto.objects.get(id=produto_id)
        usuario = request.user

        Carrinho.objects.create(usuario=usuario, produto=produto)

        return redirect('mercado:carrinho')

class RemoverCarrinhoView(LoginRequiredMixin, View):
    model = Carrinho
    success_url = 'mercado:home'

    def get(self, request, carrinho_id):
        carrinho = Carrinho.objects.get(id=carrinho_id, usuario=self.request.user)

        carrinho.delete()
        print(request)

        return redirect('mercado:carrinho')

mercado/views/HomeView.py
from django.views.generic.list import ListView
from django.views import View
from django.shortcuts import render
from mercado.models.Produto import Produto

# Dá para usar o TemplateView, não vou usar porqus estou aprendendo
class HomeView(ListView):
    template_name = 'mercado/pages/home.html'
    context_object_name = "produtos"
    model = Produto
    
    def get_queryset(self):
        return super().get_queryset().filter(is_ativo=True)

    # def get_template(self, context):
    #     try:
    #         print(self.request.user.is_vendedor)
    #     except:
    #         print('não tem vendedor aqui')

    #     return render(self.request, self.template_name, context)

    # def get(self, request):

    #     user = request.user

    #     produtos = Produto.objects.all()

    #     context = {
    #         'user': user,
    #         'produtos': produtos
    #     }

    #     return self.get_template(context)
        

mercado/views/PesquisaView.py
from mercado.models.Categoria import Categoria
from mercado.models.Produto import Produto
from django.views.generic.list import ListView
from django.db.models import Q

class PesquisaView(ListView):
    template_name = 'mercado/pages/produtos.html'
    model = Produto
    context_object_name = 'produtos'

    def get_queryset(self):
        pesquisa_separada = self.request.GET.get('q').split(' ', 1)

        if len(pesquisa_separada) > 1:
            termo_pesquisa = pesquisa_separada[1]
            tipo_pesquisa = pesquisa_separada[0].split(":")[0]
        else:
            termo_pesquisa = pesquisa_separada[0]
            tipo_pesquisa = ''

        qs = Q()

        if tipo_pesquisa == 'categoria':
            slug_da_categoria = pesquisa_separada[0].split(":")[1]
            qs = Q(Q(categoria__slug=slug_da_categoria) & Q(is_ativo=True))
        elif tipo_pesquisa == 'meus-produtos':
            qs = Q(Q(vendedor__id=self.request.user.vendedor.id) & Q(is_ativo=True))


        return super().get_queryset().filter(Q(Q(nome__icontains=termo_pesquisa)) & qs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pesquisa_pagina_atual = self.request.GET.get('q')
        pesquisa_separada = pesquisa_pagina_atual.split(' ', 1)

        if len(pesquisa_separada) > 1:
            termo_pesquisa = pesquisa_separada[1]
        else:
            termo_pesquisa = pesquisa_separada[0]

        context["titulo_da_pagina"] = f'Pesquisa por: {termo_pesquisa}'
        context["pesquisa_pagina_atual"] = pesquisa_pagina_atual

        return context

mercado/views/ProdutoView.py
from django.views import View
from django.shortcuts import render
from mercado.models.Produto import Produto

class ProdutoView(View):
    template_name = "mercado/pages/produto-detalhe.html"
    
    def get(self, request, id):
        produto = Produto.objects.get(pk=id)

        context = {
            "produto": produto
        }

        return render(request, self.template_name, context)

mercado/templates/mercado/pages/base-produtos.html
{% extends 'global/base.html' %}

{% block content %}
    {% include 'global/components/header.html' %}

    <main class="base-produtos container">
        <h1>{{ titulo_da_pagina }}</h1>
        <div class="produtos__cards">
            {% for produto in produtos %}
                {% include '../partials/cards.html' %}
            {% endfor %}
        </div>
    </main>
    
{% endblock content %}

mercado/templates/mercado/pages/carrinho.html
{% extends './base-produtos.html' %}
{% block title %}{{ titulo_da_pagina }}{% endblock title %}

{% block conteudo %}
    {% include '../partials/titulo.html' %}
    <section class="carrinho">
        <div class="carrinho__cards">
            {% for produto_carrinho in object_list %}     
                <div class="carrinho__card">
                    <div class="carrinho__card_img">
                        <img src="{{ produto_carrinho.produto.imagem.url }}" alt="{{ produto_carrinho.produto.nome }}">
                    </div>
                    <div class="carrinho__card_info">
                        <h4><small>Vendido por: </small><span>{{ produto_carrinho.produto.vendedor.nome_loja }}</span></h4>
                        <h2>{{ produto_carrinho.produto.nome }}</h2>

                        {% if produto_carrinho.produto.com_desconto %}
                            <small>Com desconto de 60% sai de R$ <span class="preco_antigo">{{ produto_carrinho.produto.get_preco }}</span></small>
                            <br>
                            <small class="preco">para: <h2>R$ {{ produto_carrinho.produto.get_preco_com_desconto }}</h2></small>
                        {% else %} 
                           
                            <small class="preco">Saindo por: <h2>R$ {{ produto_carrinho.produto.get_preco }}</h2></small>
                        {% endif %}
                    </div>
                    <div class="carrinho__card_quant">
                        <p>Quantidade:</p>
                        <div>
                            <button class="btn-icone">
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M12 4C11.4477 4 11 4.44772 11 5V11H5C4.44772 11 4 11.4477 4 12C4 12.5523 4.44772 13 5 13H11V19C11 19.5523 11.4477 20 12 20C12.5523 20 13 19.5523 13 19V13H19C19.5523 13 20 12.5523 20 12C20 11.4477 19.5523 11 19 11H13V5C13 4.44772 12.5523 4 12 4Z" fill="currentColor" /></svg>
                            </button>
                                <h3>{{ produto_carrinho.quantidade }}</h3>
                            <button class="btn-icone">
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4 12C4 11.4477 4.44772 11 5 11H19C19.5523 11 20 11.4477 20 12C20 12.5523 19.5523 13 19 13H5C4.44772 13 4 12.5523 4 12Z" fill="currentColor" /></svg>
                            </button>
                        </div>
                    </div>
                    <div class="carrinho__card_preco-total">
                        Preço total:
                        <h3 class="preco-total">R$ {{ produto_carrinho.get_preco_total_produto }}</h3>
                        <a class="btn" href="{% url 'mercado:remover-carrinho' carrinho_id=produto_carrinho.id %}">
                            Remover
                        </a>
                    </div>
                </div>        
            {% endfor %}
        </div>
        <div class="carrinho__resumo">
            <div class="carrinho__resumo_titulo">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M17 5.5H20C21.1046 5.5 22 6.39543 22 7.5V19.5C22 20.6046 21.1046 21.5 20 21.5H4C2.89543 21.5 2 20.6046 2 19.5V7.5C2 6.39543 2.89543 5.5 4 5.5H7C7 3.84315 8.34315 2.5 10 2.5H14C15.6569 2.5 17 3.84315 17 5.5ZM14 4.5H10C9.44772 4.5 9 4.94772 9 5.5H15C15 4.94772 14.5523 4.5 14 4.5ZM20 7.5H4V9.5H20V7.5ZM4 19.5V11.5H7V13.5H11V11.5H13V13.5H17V11.5H20V19.5H4Z" fill="currentColor" /></svg>
                <h1>Resumo</h1>
            </div>
            <div class="carrinho__resumo_info">
                <div>
                    <small>Valor dos produtos: </small><h4>R$ 12.000,10</h4>
                </div>
                <div>
                    <small>Frete: </small><h4>R$ 0,00</h4>
                </div>
                <div>
                    <small>Sub total: </small><h4>R$ 12.000,10</h4>
                </div>
                <small></small>
            </div>
            <div class="carrinho__resumo_btns">
                <a class="btn btn_green" href="">Ir para o pagamento</a>
                <a class="btn btn_white" href="">Continuar comprando</a>
            </div>
        </div>
    </section>
{% endblock conteudo %} 

mercado/templates/mercado/pages/form-produto.html
{% extends 'global/base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}{{ titulo_da_pagina }}{% endblock title %}

{% block content %}
    {% include 'global/components/header.html' %}

    <main class="form-produto">
        {% if form.errors %}
            {% for error in form.errors %}
                <p class="alert__error">
                    {{ error }}
                </p>                
            {% endfor %}
        {% endif %}

        <form method="post" class="form-produto__container" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-produto__container-titulo">
                {% include 'mercado/partials/titulo.html' %}
            </div>

            <div class="form-produto__campo-textos">
                {% for field in form %}
                    <label class="{{ field.field.widget.attrs.class }}">
                        <span>
                            {{ field.label }}
                            {% if field.required %}
                                <span class="requirido">*</span>
                            {% endif %}
                        </span>
                        {{ field.help_text|safe }}    

                        {% if field.name == 'imagem' %}
                            <div>
                                <span class="btn-selecionar-imagem">
                                    Selecionar imagem
                                </span>
                                <span data="imageName">
                                    Imagem.png
                                </span>
                            </div>

                            {% endif %}
                            
                            {% render_field field placeholder=field.help_text|safe %}

                            
                            {% if field.name == 'com_desconto' %}
                            <span class="toggle"></span>
                            {% endif %}
                        </label>
                        {% if field.value.url %}
                        <div class="imagem_preview">
                            Visualizar imagem
                            <img src="{{ field.value.url }}" alt="">
                            <button data="btnOpenImagePreview" class="btn" role="">
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M12 8V6H8V10H10V8H12Z" fill="currentColor" /><path d="M14 14H16V18H12V16H14V14Z" fill="currentColor" /><path fill-rule="evenodd" clip-rule="evenodd" d="M4 3C4 2.44772 4.44772 2 5 2H19C19.5523 2 20 2.44772 20 3V21C20 21.5523 19.5523 22 19 22H5C4.44772 22 4 21.5523 4 21V3ZM6 20V4H18V20H6Z" fill="currentColor" /></svg>
                            </button>

                            <div data="modalPreviewImage" class="modal-imagem_preview">
                                <button data="btnCloseImagePreview" class="btn">
                                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6.2253 4.81108C5.83477 4.42056 5.20161 4.42056 4.81108 4.81108C4.42056 5.20161 4.42056 5.83477 4.81108 6.2253L10.5858 12L4.81114 17.7747C4.42062 18.1652 4.42062 18.7984 4.81114 19.1889C5.20167 19.5794 5.83483 19.5794 6.22535 19.1889L12 13.4142L17.7747 19.1889C18.1652 19.5794 18.7984 19.5794 19.1889 19.1889C19.5794 18.7984 19.5794 18.1652 19.1889 17.7747L13.4142 12L19.189 6.2253C19.5795 5.83477 19.5795 5.20161 19.189 4.81108C18.7985 4.42056 18.1653 4.42056 17.7748 4.81108L12 10.5858L6.2253 4.81108Z" fill="currentColor" /></svg>
                                </button>
                                <div>
                                    <img src="{{ field.value.url }}" alt="">
                                </div>
                            </div>
                        </div>
                        {% endif %}    
                    {% if field.errors %}
                        {% for error in field.errors %}
                            <p class="form_error">
                                {{ error }}  
                            </p>     
                        {% endfor %}
                    {% endif %}
                {% endfor %}
            </div>
                
            <div class="form-produto__btns">
                <button type="submit" class="btn btn_green">
                    Salvar
                </button>
                <a class="btn_white" href="{% url 'mercado:home' %}">Voltar</a>
            </div>
        </form>
    </main>
    
    <script type="module" src="{% static 'global/js/form-produto.js' %}"></script>
{% endblock content %}

mercado/templates/mercado/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home   {% endblock title %}

{% block content %}
    {% include 'global/components/header.html' %}
    <main class="home">
        <div class="container">
            {% include 'global/components/messages.html' %}

            <div class="lista-cards">
                {% for produto in produtos %}
                    {% include '../partials/cards.html' %}
                {% endfor %}
            </div>
        </div>
        <div class="home__categoria"></div>
    </main>
{% endblock content %}

mercado/templates/mercado/pages/meus-produtos.html
{% extends 'global/base.html' %}

{% block title %}Meus produtos{% endblock title %}

{% block content %}
    {% include 'global/components/header.html' %}

    <main class="base-produtos container">
        <h1>Olá, {{ user.get_full_name }}</h1>
        <div class="dash_meus-produtos">
            <div class="dash_meus-produtos_todos">
                <h3>
                    Produtos cadastrados
                </h3>
                <h1>
                    {{ quantidade_produtos }}
                </h1>
            </div>
            <div class="dash_meus-produtos_ativos">
                <h3>
                    Produtos ativos
                </h3>
                <h1>
                    {{ quantidade_produtos_ativos }}
                </h1>
            </div>
            <div class="dash_meus-produtos_desativos">
                <h3>
                    Produtos cadastrados
                </h3>
                <h1>
                    {{ quantidade_produtos_desativos }}
                </h1>
            </div>
        </div>
        <div class="produtos__cards">
            {% for produto in produtos %}
                {% include '../partials/meus-produto-cards.html' %}
            {% empty %}
                <h1>Você não cadastrou nenhum produto</h1>
            {% endfor %}
        </div>
    </main>
    
{% endblock content %}      

mercado/templates/mercado/pages/produto-detalhe.html
{% extends 'global/base.html' %}

{% block content %}
    {% include 'global/components/header.html' %}
    <main class="produto">
    <div class="produto__layout">
        <div class="produto__layout_imgs center">
            <img src="{{ produto.imagem.url }}" alt="{{ produto.nome }}">
        </div>
        <div class="produto__layout_info">
            <div class="info__description">
                <h1>{{ produto.nome }}</h1>
                <p>{{ produto.descricao }}</p>
            </div>
            <div class="info__price">
                <div>
                    <h2>Preço</h2>
                    {% if produto.com_desconto is True %}
                        <h3 class="card__info_price_old">R$ {{ produto.get_preco }}</h3>
                        <h1 class="card__info_price">R$ {{ produto.get_preco_com_desconto }}</h1>
                    {% else %}
                        <h1><span>R$</span> {{ produto.get_preco }}</h1>
                    {% endif %}
                </div>
                <div>
                    <span>Vendido por: </span>
                    <span>{{ produto.vendedor }}</span>
                </div>
            </div>
            <div class="info__btns">
                <a href="{% url 'mercado:adicionar-carrinho' produto_id=produto.id %}" class="btn_white">Adicionar ao carrinho</a>
                <a href="" class="btn_green">Comprar agora</a>
            </div>
        </div>
    </div>
    <div class="produto__detalhe">
        <h1>Detalhe do produto</h1>
        <div class="center">
            {{ produto.descricao_html|safe }}
        </div>
    </div>
    </main>
{% endblock content %}

mercado/templates/mercado/pages/produtos.html
{% extends 'global/base.html' %}

{% load static %}

{% block title %}{{ titulo_da_pagina }}{% endblock title %}

{% block content %}
    {% include 'global/components/header.html' %}

    <main class="base-produtos container">
        <h1>{{ titulo_da_pagina }}</h1>
        <div class="produtos__cards">
            {% for produto in produtos %}
                {% include '../partials/cards.html' %}
            {% empty %}
                <div class="nada-encontrado">
                    <img src="{% static '/global/image/not-found.png' %}" alt="Cones sinalizando que nada foi encontrado"/> 
                </div>
            {% endfor %}
        </div>
    </main>
    
{% endblock content %}  